import mongoose from "mongoose";

const savedReportSchema = new mongoose.Schema(
  {
    templateId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ReportTemplate",
      required: true
    },

    businessId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Business",
      required: true
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    appliedFilters: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    },

    snapshotData: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
      /*
        The full analytics data at the moment of generation.
        Helpful for historical or scheduled reports.
      */
    },

    fileUrl: {
      type: String,
      required: false // S3 URL or local filesystem
    },

    fileType: {
      type: String,
      enum: ["pdf", "excel", "csv"],
      default: "pdf"
    },

    generatedAt: {
      type: Date,
      default: Date.now
    },

    isScheduled: {
      type: Boolean,
      default: false // auto-generated by cron jobs
    },

    scheduleInfo: {
      type: mongoose.Schema.Types.Mixed,
      default: null
      /*
        Example:
        {
          scheduleId: "cron_abc123",
          frequency: "monthly"
        }
      */
    },

    isActive: {
      type: Boolean,
      default: true
    }
  },
  { timestamps: true }
);

savedReportSchema.index({ businessId: 1 });
savedReportSchema.index({ templateId: 1 });
savedReportSchema.index({ userId: 1 });

const SavedReport = mongoose.model("SavedReport", savedReportSchema);
export default SavedReport;
